    <aside id="sidebar">
        <ul>
            <li class="active">
                <a href="http://localhost/VSGA/index.php?page=anggota">Data Anggota</a>
            </li>
            <li class="">
                <a href="http://localhost/VSGA/index.php?page=buku">Data Buku</a>
            </li>
            <li>
                <a href="http://localhost/VSGA/index.php?page=peminjaman">Data Peminjaman</a>
            </li>
        </ul>
    </aside>


?>